# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Xcode Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Install dependencies (if using CocoaPods)
        run: |
          if [ -f "Podfile" ]; then
            pod install --repo-update
          fi
        working-directory: WeatherApp

      - name: Build and Test
        run: |
          xcodebuild test \
            -workspace WeatherApp.xcworkspace \
            -scheme WeatherApp \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
