name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-14  # Usa la última versión de macOS con Xcode 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Install dependencies (if using CocoaPods)
        run: |
          if [ -f "Podfile" ]; then
            pod install --repo-update
          fi

      - name: Build and run unit tests
        run: |
          xcodebuild test \
            -workspace WeatherApp.xcworkspace \  # Si usas xcworkspace
            -scheme WeatherApp \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-test-results
          path: ~/Library/Logs/DiagnosticReports
